# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.7.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QLineEdit,
    QListWidget, QListWidgetItem, QMainWindow, QMenu,
    QMenuBar, QPushButton, QSizePolicy, QStatusBar,
    QTextEdit, QToolButton, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(814, 635)
        self.actionMenu = QAction(MainWindow)
        self.actionMenu.setObjectName(u"actionMenu")
        self.actionTheme = QAction(MainWindow)
        self.actionTheme.setObjectName(u"actionTheme")
        self.actionClear = QAction(MainWindow)
        self.actionClear.setObjectName(u"actionClear")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 10, 781, 361))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Sunken)
        self.SOD = QLineEdit(self.frame)
        self.SOD.setObjectName(u"SOD")
        self.SOD.setGeometry(QRect(20, 190, 251, 31))
        self.SAD = QLineEdit(self.frame)
        self.SAD.setObjectName(u"SAD")
        self.SAD.setGeometry(QRect(20, 90, 251, 31))
        self.SAD.setClearButtonEnabled(False)
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 10, 291, 31))
        font = QFont()
        font.setFamilies([u"Source Code Pro"])
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setScaledContents(True)
        self.label_2 = QLabel(self.frame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 50, 251, 31))
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setScaledContents(True)
        self.label_3 = QLabel(self.frame)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 150, 251, 31))
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setScaledContents(True)
        self.label_4 = QLabel(self.frame)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(490, 50, 251, 31))
        self.label_4.setFont(font)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setScaledContents(True)
        self.label_5 = QLabel(self.frame)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(490, 250, 251, 31))
        self.label_5.setFont(font)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setScaledContents(True)
        self.micCount = QLineEdit(self.frame)
        self.micCount.setObjectName(u"micCount")
        self.micCount.setGeometry(QRect(490, 290, 251, 31))
        self.label_6 = QLabel(self.frame)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 250, 251, 31))
        self.label_6.setFont(font)
        self.label_6.setAutoFillBackground(False)
        self.label_6.setScaledContents(True)
        self.totalSpread = QLineEdit(self.frame)
        self.totalSpread.setObjectName(u"totalSpread")
        self.totalSpread.setGeometry(QRect(20, 290, 251, 31))
        self.saveButton = QPushButton(self.frame)
        self.saveButton.setObjectName(u"saveButton")
        self.saveButton.setGeometry(QRect(320, 280, 121, 51))
        self.saveButton.setAcceptDrops(False)
        self.label_7 = QLabel(self.frame)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(490, 150, 251, 31))
        self.label_7.setFont(font)
        self.label_7.setAutoFillBackground(False)
        self.label_7.setScaledContents(True)
        self.typeButton = QToolButton(self.frame)
        self.typeButton.setObjectName(u"typeButton")
        self.typeButton.setGeometry(QRect(490, 90, 251, 31))
        self.noiseButton = QToolButton(self.frame)
        self.noiseButton.setObjectName(u"noiseButton")
        self.noiseButton.setGeometry(QRect(490, 190, 251, 31))
        self.recordButton = QPushButton(self.centralwidget)
        self.recordButton.setObjectName(u"recordButton")
        self.recordButton.setGeometry(QRect(10, 390, 111, 41))
        self.recordButton.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.MediaRecord))
        self.recordButton.setIcon(icon)
        self.refreshList = QToolButton(self.centralwidget)
        self.refreshList.setObjectName(u"refreshList")
        self.refreshList.setGeometry(QRect(270, 390, 111, 41))
        self.deleteFile = QToolButton(self.centralwidget)
        self.deleteFile.setObjectName(u"deleteFile")
        self.deleteFile.setGeometry(QRect(140, 390, 111, 41))
        self.listView = QListWidget(self.centralwidget)
        self.listView.setObjectName(u"listView")
        self.listView.setGeometry(QRect(410, 390, 381, 192))
        self.consoleLog = QTextEdit(self.centralwidget)
        self.consoleLog.setObjectName(u"consoleLog")
        self.consoleLog.setGeometry(QRect(10, 440, 391, 141))
        self.consoleLog.setReadOnly(True)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 814, 25))
        self.menuRecord_Application = QMenu(self.menubar)
        self.menuRecord_Application.setObjectName(u"menuRecord_Application")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuRecord_Application.menuAction())
        self.menuRecord_Application.addAction(self.actionMenu)
        self.menuRecord_Application.addAction(self.actionClear)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionMenu.setText(QCoreApplication.translate("MainWindow", u"Import File", None))
        self.actionTheme.setText(QCoreApplication.translate("MainWindow", u"Theme", None))
        self.actionClear.setText(QCoreApplication.translate("MainWindow", u"Clear Console", None))
        self.SAD.setPlaceholderText("")
        self.label.setText(QCoreApplication.translate("MainWindow", u"Enter the following:", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"SAD", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"SOD", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Type", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Mic Count", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Total Spread", None))
        self.saveButton.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Noise", None))
        self.typeButton.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.noiseButton.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.recordButton.setText(QCoreApplication.translate("MainWindow", u" Record", None))
        self.refreshList.setText(QCoreApplication.translate("MainWindow", u"Refresh List", None))
        self.deleteFile.setText(QCoreApplication.translate("MainWindow", u"Delete File", None))
        self.menuRecord_Application.setTitle(QCoreApplication.translate("MainWindow", u"Settings", None))
    # retranslateUi

